name: "Build"
'on':
  push:
    branches:
      - main
      - master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - '**'

jobs:
  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
        cuda: ["on", "off"]
        include:
          - cuda: "off"
            cmake_args: |
              -DTASK_SPOOLER_COMPILE_CUDA=off

          - cuda: "on"
            cmake_args: ""

      fail-fast: false

    name: "cmake / ${{ matrix.os }} / cuda-${{ matrix.cuda }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Install CUDA"
        if: ${{ matrix.cuda == 'on' }}
        run: |
          sudo apt-get update
          sudo apt-get -y install nvidia-cuda-toolkit

      - name: "Build"
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.cmake_args }}
          make 


  build-macos:
    strategy:
      matrix:
        os: [macos-latest]
      fail-fast: false

    name: "cmake / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Build"
        run: |
          mkdir build
          cd build
          cmake .. -DTASK_SPOOLER_COMPILE_CUDA=off
          make 


